Пишем первую функцию
htmlacademy-php/1480825-doingsdone-12 pull request #4
Opened 2020-06-28 08:34 UTC by SidMorgan

2020-06-29 12:18 UTC, samoilenkoevgeniy requested changes
Привет! Давай переименуем ключи нашего массива $tasks на английские, и в сравнении в нашей функции будем использовать так же английский вариант

2020-07-01 16:47 UTC, SidMorgan commented
Привет! Да, без проблем.

2020-07-02 09:11 UTC, samoilenkoevgeniy requested changes
Совсем чуть-чуть исправить именования переменных и все!)

2020-07-02 09:11 UTC, SamoilenkoEvgeniy commented on index.php
> +		foreach ($tasks as $taskProperty => $taskPropertyValue) {
$taskProperty здесь не используется. Можно ее убрать.
foreach($tasks as $taskPropertyValue) { ...

2020-07-02 09:11 UTC, SamoilenkoEvgeniy commented on index.php
> +		foreach ($tasks as $taskProperty => $taskPropertyValue) {
И переменную тогда можно назвать просто $task

2020-07-03 15:50 UTC, SidMorgan commented on index.php
> +		foreach ($tasks as $taskProperty => $taskPropertyValue) {
видимо, так)

2020-07-04 11:13 UTC, samoilenkoevgeniy approved these changes

2020-07-04 11:13 UTC, merged