Шаблонизируем проект
htmlacademy-php/1480825-doingsdone-12 pull request #5
Opened 2020-07-13 17:26 UTC by SidMorgan

2020-07-21 10:30 UTC, samoilenkoevgeniy requested changes
Давай немного разберёмся с отступами и пойдём дальше!

В остальном все хорошо.

2020-07-21 10:30 UTC, SamoilenkoEvgeniy commented on templates/main.php
> +	<?php foreach ($tasks as $taskProperty => $taskPropertyValue): {
Давай разберёмся здесь с отступами. 
Каждый новый блок должен быть на новой строке. 
<?php
Foreach....

2020-07-24 16:38 UTC, SidMorgan commented on templates/main.php
> +	<?php foreach ($tasks as $taskProperty => $taskPropertyValue): {
В смысле, не делать лишней строки отступа? Тут немного не понял.

2020-07-25 16:37 UTC, samoilenkoevgeniy requested changes

2020-07-25 16:37 UTC, SamoilenkoEvgeniy commented on templates/main.php
> +	<?php foreach ($tasks as $taskProperty => $taskPropertyValue): {
<?php foreach ($tasks as $taskProperty => $taskPropertyValue): {
			if($taskPropertyValue['done'] == true && $show_complete_tasks == 0) continue; 
} ?>
Как-то так.

2020-07-25 16:37 UTC, SamoilenkoEvgeniy commented on templates/main.php
> +	<?php foreach ($tasks as $taskProperty => $taskPropertyValue): {
Тут не получается с табуляцией показать. Попробуй просто сделать авто форматирование в этом файле.

2020-07-27 15:15 UTC, SidMorgan commented on templates/main.php
> +	<?php foreach ($tasks as $taskProperty => $taskPropertyValue): {
ну как-то так

2020-07-28 05:35 UTC, samoilenkoevgeniy approved these changes

2020-07-28 05:36 UTC, merged